import { ArtifactType, PassSpec } from '../types';

const passRegistry: Record<string, PassSpec> = {
  '0.0': {
    id: '0.0',
    phase: 'reduction',
    name: 'Project Regrounding',
    description: 'Assess and distill the teleplay source into a unified authoritative project state.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'show', selector: 'characters' }
    ],
    promptTemplateId: 'p_0_0_regrounding',
    parserId: 'regrounding_brief',
    outputArtifactType: ArtifactType.REGROUNDING_BRIEF,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: {
      enabled: false,
      proseGuidance: {}
    },
    requires: []
  },
  '0.1': {
    id: '0.1',
    phase: 'reduction',
    name: 'Engine Read',
    description: 'Identify and lock the core conflict engine, antagonist mode, genre lane, and visual world.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF }
    ],
    promptTemplateId: 'p_0_1_engine_read',
    parserId: 'engine_read',
    outputArtifactType: ArtifactType.ENGINE_READ,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Ensure the tone is tense, authentic to military operations, and respects historical stakes as a war drama.',
        'comedy_deadpan': 'Ensure the engine highlights absurdity, dry comedic situational tension, and character eccentricities.'
      }
    },
    requires: [ArtifactType.REGROUNDING_BRIEF]
  },
  '0.2': {
    id: '0.2',
    phase: 'reduction',
    name: "What's Working Inventory",
    description: 'Catalog existing dramatic assets, characters, and set pieces in the teleplay draft that must be protected.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ }
    ],
    promptTemplateId: 'p_0_2_working_inventory',
    parserId: 'working_inventory',
    outputArtifactType: ArtifactType.WORKING_INVENTORY,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.6,
    registerFraming: {
      enabled: false,
      proseGuidance: {}
    },
    requires: [ArtifactType.REGROUNDING_BRIEF, ArtifactType.ENGINE_READ]
  },
  '0.3': {
    id: '0.3',
    phase: 'reduction',
    name: 'Repetition Diagnosis',
    description: 'Identify repeated scene functions and scene-dump patterns. Flag which scenes repeat without escalation.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ },
      { kind: 'artifact', type: ArtifactType.WORKING_INVENTORY },
    ],
    promptTemplateId: 'p_0_3_repetition_diagnosis',
    parserId: 'repetition_diagnosis',
    outputArtifactType: ArtifactType.REPETITION_DIAGNOSIS,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Repetition in a war drama must escalate stakes or troop condition. Atmospheric repetition that deepens dread is acceptable only if it advances a character or moral question.',
        'comedy_deadpan': 'Comedic repetition may be structural (running gags, callback rhythms). Flag only repetition that does not build toward a payoff or escalation.'
      }
    },
    requires: [ArtifactType.REGROUNDING_BRIEF, ArtifactType.ENGINE_READ, ArtifactType.WORKING_INVENTORY]
  },
  '0.4': {
    id: '0.4',
    phase: 'reduction',
    name: 'Form-Function Audit',
    description: 'Scene-by-scene audit of intention, conflict, turn, consequence, and visual function. Separates structure from atmosphere.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.WORKING_INVENTORY },
      { kind: 'artifact', type: ArtifactType.REPETITION_DIAGNOSIS },
    ],
    promptTemplateId: 'p_0_4_form_function_audit',
    parserId: 'form_function_audit',
    outputArtifactType: ArtifactType.FORM_FUNCTION_AUDIT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Scenes that establish operational reality or troop morale counts as structural if they change the characters readiness or belief, not just the mood.',
        'comedy_deadpan': 'Scenes that are pure tone or atmosphere are acceptable if they establish the comic register. Flag them as tone rather than cut.'
      }
    },
    requires: [ArtifactType.REGROUNDING_BRIEF, ArtifactType.REPETITION_DIAGNOSIS]
  },
  '0.5': {
    id: '0.5',
    phase: 'reduction',
    name: 'Character Function Audit',
    description: 'Audit each major character for repeated behavior patterns versus arc movement. Identify flattening risks and what each character needs per section.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ },
      { kind: 'artifact', type: ArtifactType.WORKING_INVENTORY },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_5_character_function_audit',
    parserId: 'character_function_audit',
    outputArtifactType: ArtifactType.CHARACTER_FUNCTION_AUDIT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.5,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Characters must be evaluated on whether their military or moral competence is tested, not just stated. Stoicism is not an arc.',
        'comedy_deadpan': 'Comedic characters may repeat behaviors as part of their comic engine. Flag repetition only when it forecloses surprise or character revelation.'
      }
    },
    requires: [ArtifactType.REGROUNDING_BRIEF, ArtifactType.ENGINE_READ, ArtifactType.WORKING_INVENTORY]
  },
  '0.6': {
    id: '0.6',
    phase: 'reduction',
    name: 'Premise Cash-Out',
    description: 'Audit whether the title and premise actually organize each issue as a specific dramatic problem. Reformulate vague premises.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
    ],
    promptTemplateId: 'p_0_6_premise_cashout',
    parserId: 'premise_cashout',
    outputArtifactType: ArtifactType.PREMISE_CASHOUT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.5,
    registerFraming: {
      enabled: false,
      proseGuidance: {}
    },
    requires: [ArtifactType.REGROUNDING_BRIEF, ArtifactType.ENGINE_READ, ArtifactType.CHARACTER_FUNCTION_AUDIT]
  },
  '0.7': {
    id: '0.7',
    phase: 'reduction',
    name: 'Keep / Cut / Consolidate Orders',
    description: 'Convert all diagnostic passes into executable revision direction: what to keep, cut, consolidate, limit, and compress.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.WORKING_INVENTORY },
      { kind: 'artifact', type: ArtifactType.REPETITION_DIAGNOSIS },
      { kind: 'artifact', type: ArtifactType.FORM_FUNCTION_AUDIT },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
      { kind: 'artifact', type: ArtifactType.PREMISE_CASHOUT },
    ],
    promptTemplateId: 'p_0_7_keep_cut_orders',
    parserId: 'keep_cut_orders',
    outputArtifactType: ArtifactType.KEEP_CUT_ORDERS,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Keep material that establishes operational reality, character under pressure, and moral cost. Cut material that is only action spectacle without consequence.',
        'comedy_deadpan': 'Keep material that establishes the comic register, the bureaucratic or absurdist world logic, and character eccentricity. Cut material that breaks register or explains jokes.'
      }
    },
    requires: [
      ArtifactType.REPETITION_DIAGNOSIS,
      ArtifactType.FORM_FUNCTION_AUDIT,
      ArtifactType.CHARACTER_FUNCTION_AUDIT,
      ArtifactType.PREMISE_CASHOUT
    ]
  },
  '0.8': {
    id: '0.8',
    phase: 'arc_lock',
    name: 'Clean Spine Proposal',
    description: 'Using the strongest material and keep/cut orders, build one clean act/section spine. First synthesis pass.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ },
      { kind: 'artifact', type: ArtifactType.WORKING_INVENTORY },
      { kind: 'artifact', type: ArtifactType.KEEP_CUT_ORDERS },
    ],
    promptTemplateId: 'p_0_8_clean_spine',
    parserId: 'clean_spine',
    outputArtifactType: ArtifactType.CLEAN_SPINE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Structure the spine so each act advances the military or moral situation. The spine must show escalating operational pressure alongside character cost.',
        'comedy_deadpan': 'Structure the spine so each act escalates the absurdist situation while tightening the bureaucratic or social trap around the characters.'
      }
    },
    requires: [ArtifactType.KEEP_CUT_ORDERS]
  },
  '0.8A': {
    id: '0.8A',
    phase: 'arc_lock',
    name: 'Arc Imagination / Issue Ladder',
    description: 'Determine natural arc length (4/6/8 issues) and build the full issue ladder. Reads scopeIssueCount from run for guidance.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ENGINE_READ },
      { kind: 'artifact', type: ArtifactType.CLEAN_SPINE },
    ],
    promptTemplateId: 'p_0_8a_arc_ladder',
    parserId: 'arc_ladder',
    outputArtifactType: ArtifactType.ARC_LADDER,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: {
      enabled: true,
      proseGuidance: {
        'war_drama': 'Each issue must change the operational and moral situation. The arc climax must force a choice between survival and principle.',
        'comedy_deadpan': 'Each issue must tighten the absurdist trap. Climax types should rotate: bureaucratic impasse, personal humiliation, accidental escalation, systemic collapse.'
      }
    },
    requires: [ArtifactType.CLEAN_SPINE]
  },
  '0.8R': {
    id: '0.8R',
    phase: 'arc_lock',
    name: 'Spine Revision',
    description: 'Incorporate author notes and directives into a revised version of the Clean Spine.',
    scope: 'arc',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.CLEAN_SPINE },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
    ],
    promptTemplateId: 'p_0_8r_spine_revision',
    parserId: 'clean_spine',
    outputArtifactType: ArtifactType.CLEAN_SPINE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    manual: true,
    registerFraming: {
      enabled: false,
      proseGuidance: {}
    },
    requires: [ArtifactType.CLEAN_SPINE, ArtifactType.ARC_LADDER]
  },
  '0.8RA': {
    id: '0.8RA',
    phase: 'arc_lock',
    name: 'Ladder Revision',
    description: 'Incorporate author notes and directives into a revised version of the Arc Ladder.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.CLEAN_SPINE },
    ],
    promptTemplateId: 'p_0_8ra_ladder_revision',
    parserId: 'arc_ladder',
    outputArtifactType: ArtifactType.ARC_LADDER,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    manual: true,
    registerFraming: {
      enabled: false,
      proseGuidance: {}
    },
    requires: [ArtifactType.ARC_LADDER, ArtifactType.CLEAN_SPINE]
  },
  '0.9': {
    id: '0.9', phase: 'rebuild', name: 'Anchored Rebuild Conversation',
    description: 'Generate all issues with structural pillars first, bridges between them.',
    scope: 'episode-anchored',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.KEEP_CUT_ORDERS },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_9_clean_issue',
    parserId: 'issue_draft',
    outputArtifactType: ArtifactType.ISSUE_DRAFT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'war_drama': 'Draft in the register of a grounded war drama. Scenes must carry operational weight and moral cost.',
      'comedy_deadpan': 'Draft in the register of deadpan bureaucratic comedy. Dialogue should be dry, situations should escalate absurdly.',
    }},
    requires: [ArtifactType.ARC_LADDER, ArtifactType.KEEP_CUT_ORDERS],
  },
  '0.9S': {
    id: '0.9S', phase: 'rebuild', name: 'Scene Structure Extraction',
    description: 'Group the beat spine into Acts and Scenes with scene-level context.',
    scope: 'episode',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'current' }
    ],
    promptTemplateId: 'p_0_9s_structure',
    parserId: 'scene_structure',
    outputArtifactType: ArtifactType.SCENE_STRUCTURE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.5,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.ISSUE_DRAFT],
  },
  '0.9W': {
    id: '0.9W', phase: 'rebuild', name: 'Scene Writing',
    description: 'Write each scene in full as a screenplay, voiced and decompressed.',
    scope: 'episode',
    inputs: [
      { kind: 'artifact', type: ArtifactType.SCENE_STRUCTURE, episodeRef: 'current' },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_9w_scene_script',
    parserId: 'scene_script',
    outputArtifactType: ArtifactType.SCENE_SCRIPT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'comedy_deadpan': 'Dialogue must be dry, flat, and procedurally absurd. Characters speak in bureaucratic register. Comedy arrives through tone gap and systemic indifference, not jokes.',
      'war_drama': 'Dialogue must carry operational weight. Characters speak under pressure. Subtext is more important than text.',
    }},
    requires: [ArtifactType.SCENE_STRUCTURE],
  },
  '0.9G': {
    id: '0.9G', phase: 'rebuild', name: 'Scene Segmentation',
    description: 'Break the written scenes into page beats, preserving the lines verbatim.',
    scope: 'episode',
    inputs: [
      { kind: 'artifact', type: ArtifactType.SCENE_SCRIPT, episodeRef: 'current' },
      { kind: 'artifact', type: ArtifactType.SCENE_STRUCTURE, episodeRef: 'current' },
    ],
    promptTemplateId: 'p_0_9g_segmentation',
    parserId: 'segmentation_plan',
    outputArtifactType: ArtifactType.SCENE_STRUCTURE,  // bridge-compatible
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: { enabled: true, proseGuidance: {
      'comedy_deadpan': 'Dialogue must be dry, flat, and procedurally absurd. Characters speak in bureaucratic register. Comedy arrives through tone gap and systemic indifference, not jokes.',
      'war_drama': 'Dialogue must carry operational weight. Characters speak under pressure. Subtext is more important than text.',
    }},
    requires: [ArtifactType.SCENE_SCRIPT, ArtifactType.SCENE_STRUCTURE],
  },
  '0.9A': {
    id: '0.9A', phase: 'rebuild', name: 'Character Care Scene Pool',
    description: 'Build a modular pool of short scenes that make readers care about the cast.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.REGROUNDING_BRIEF },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_9a_scene_pool',
    parserId: 'scene_pool',
    outputArtifactType: ArtifactType.SCENE_POOL_ENTRY,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'war_drama': 'Character care scenes should reveal competence, dark humor, loyalty, or grief under operational conditions.',
      'comedy_deadpan': 'Character care scenes should reveal eccentricity, failed coping mechanisms, and absurd expertise.',
    }},
    requires: [ArtifactType.ARC_LADDER, ArtifactType.CHARACTER_FUNCTION_AUDIT],
  },
  '0.10': {
    id: '0.10', phase: 'rebuild', name: 'Output State / Next-Issue Handoff',
    description: 'Capture what changed at the end of the issue and what the next issue inherits.',
    manual: true,
    scope: 'episode',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'current' },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
    ],
    promptTemplateId: 'p_0_10_output_state',
    parserId: 'output_state',
    outputArtifactType: ArtifactType.OUTPUT_STATE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.ISSUE_DRAFT, ArtifactType.ARC_LADDER],
  },
  '0.11': {
    id: '0.11', phase: 'rebuild', name: 'Sequential Issue Build',
    description: 'Build each subsequent issue honoring the prior output state and preparing the next.',
    manual: true,
    scope: 'episode',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.OUTPUT_STATE, episodeRef: 'prior' },
      { kind: 'artifact', type: ArtifactType.KEEP_CUT_ORDERS },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_11_sequential_build',
    parserId: 'issue_draft',
    outputArtifactType: ArtifactType.ISSUE_DRAFT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'war_drama': 'Each issue must advance both operational and moral deterioration. The double hinge rule: pay off one prior consequence, create one unavoidable forward pressure.',
      'comedy_deadpan': 'Each issue must tighten the bureaucratic trap. Pay off one prior absurdity, escalate one new systemic failure.',
    }},
    requires: [ArtifactType.ARC_LADDER, ArtifactType.OUTPUT_STATE],
  },
  '0.12': {
    id: '0.12', phase: 'rebuild', name: 'Finale Lock',
    description: 'Confirm the penultimate issue creates unavoidable conditions for the finale.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'prior' },
    ],
    promptTemplateId: 'p_0_12_finale_lock',
    parserId: 'finale_lock',
    outputArtifactType: ArtifactType.FINALE_LOCK,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.5,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.ARC_LADDER, ArtifactType.ISSUE_DRAFT],
  },
  '0.13': {
    id: '0.13', phase: 'rebuild', name: 'Finale Build',
    description: 'Build the final issue so it is both a climactic high and a satisfying resolution.',
    manual: true,
    scope: 'episode',
    inputs: [
      { kind: 'source', selector: 'full' },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.FINALE_LOCK },
      { kind: 'artifact', type: ArtifactType.OUTPUT_STATE, episodeRef: 'prior' },
      { kind: 'artifact', type: ArtifactType.SCENE_POOL_ENTRY },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_0_13_finale_build',
    parserId: 'issue_draft',
    outputArtifactType: ArtifactType.ISSUE_DRAFT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'war_drama': 'The finale must resolve the moral question through action, not speech. Victory must preserve cost.',
      'comedy_deadpan': 'The finale must prove the absurd system is permanent but the characters have changed their relationship to it.',
    }},
    requires: [ArtifactType.FINALE_LOCK, ArtifactType.OUTPUT_STATE],
  },
  '0.14': {
    id: '0.14', phase: 'rebuild', name: 'Arc Closure Verification',
    description: 'Audit the completed finale against the full arc to verify all threads are paid off.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.FINALE_LOCK },
    ],
    promptTemplateId: 'p_0_14_arc_closure',
    parserId: 'arc_closure',
    outputArtifactType: ArtifactType.ARC_CLOSURE_REPORT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.4,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.FINALE_LOCK, ArtifactType.ARC_LADDER],
  },
  '1': {
    id: '1', phase: 'rebuild', name: 'Emotional Question Pass',
    description: 'Identify the deeper emotional question beneath the plot and apply it across each issue.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
    ],
    promptTemplateId: 'p_1_emotional_question',
    parserId: 'emotional_question',
    outputArtifactType: ArtifactType.EMOTIONAL_QUESTION,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.ARC_CLOSURE_REPORT],
  },
  '2': {
    id: '2', phase: 'rebuild', name: 'Private Wound Pass',
    description: 'Define each character\'s private wound and audit where it surfaces through behavior.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_2_private_wound',
    parserId: 'private_wound',
    outputArtifactType: ArtifactType.PRIVATE_WOUND,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.EMOTIONAL_QUESTION],
  },
  '3': {
    id: '3', phase: 'rebuild', name: 'Emotional Page-Turn Pass',
    description: 'Ensure each issue pulls the reader forward emotionally, not just informationally.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.EMOTIONAL_QUESTION },
    ],
    promptTemplateId: 'p_3_page_turn',
    parserId: 'page_turn_map',
    outputArtifactType: ArtifactType.PAGE_TURN_MAP,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.6,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.EMOTIONAL_QUESTION],
  },
  '4': {
    id: '4', phase: 'rebuild', name: 'Nobody Is Fully Right Pass',
    description: 'Strengthen conflicts so scenes become value-versus-value instead of hero-versus-obstacle.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
    ],
    promptTemplateId: 'p_4_nobody_right',
    parserId: 'balanced_conflict',
    outputArtifactType: ArtifactType.BALANCED_CONFLICT,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.PRIVATE_WOUND],
  },
  '5': {
    id: '5', phase: 'rebuild', name: 'Relationship Pressure Pass',
    description: 'Make character relationships evolve through pressure, not generic bonding.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.PRIVATE_WOUND },
      { kind: 'show', selector: 'characters' },
    ],
    promptTemplateId: 'p_5_relationship_pressure',
    parserId: 'relationship_pressure',
    outputArtifactType: ArtifactType.RELATIONSHIP_PRESSURE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.BALANCED_CONFLICT],
  },
  '6': {
    id: '6', phase: 'enrichment', name: 'Visual Motif Pass',
    description: 'Create recurring visual-emotional language from objects, gestures, and spaces.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
      { kind: 'artifact', type: ArtifactType.RELATIONSHIP_PRESSURE },
    ],
    promptTemplateId: 'p_6_visual_motif',
    parserId: 'visual_motif',
    outputArtifactType: ArtifactType.VISUAL_MOTIF,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.8,
    registerFraming: { enabled: true, proseGuidance: {
      'war_drama': 'Visual motifs should emerge from operational objects: weapons, maps, rations, wounds, insignia.',
      'comedy_deadpan': 'Visual motifs should emerge from bureaucratic objects: forms, rubber stamps, fluorescent lighting, clipboards.',
    }},
    requires: [ArtifactType.RELATIONSHIP_PRESSURE],
  },
  '7': {
    id: '7', phase: 'enrichment', name: 'Quiet Panel Pass',
    description: 'Plan silent or near-silent panels that carry emotional weight without dialogue.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.VISUAL_MOTIF },
      { kind: 'artifact', type: ArtifactType.PRIVATE_WOUND },
    ],
    promptTemplateId: 'p_7_quiet_panel',
    parserId: 'quiet_panel_plan',
    outputArtifactType: ArtifactType.QUIET_PANEL_PLAN,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.VISUAL_MOTIF],
  },
  '8': {
    id: '8', phase: 'enrichment', name: 'Page Rhythm Pass',
    description: 'Audit for page rhythm — identify where the story needs more space, less dialogue, or stronger visual turns.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.QUIET_PANEL_PLAN },
    ],
    promptTemplateId: 'p_8_page_rhythm',
    parserId: 'page_rhythm',
    outputArtifactType: ArtifactType.PAGE_RHYTHM,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.6,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.QUIET_PANEL_PLAN],
  },
  '9': {
    id: '9', phase: 'enrichment', name: 'Emotional Callback Map',
    description: 'Map objects, lines, gestures, and motifs seeded early that must be paid off later.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.VISUAL_MOTIF },
      { kind: 'artifact', type: ArtifactType.ARC_LADDER },
    ],
    promptTemplateId: 'p_9_callback_map',
    parserId: 'callback_map',
    outputArtifactType: ArtifactType.CALLBACK_MAP,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.PAGE_RHYTHM],
  },
  '10': {
    id: '10', phase: 'enrichment', name: 'Earned-Line Pass',
    description: 'Give each major character one line they could not honestly say at the beginning.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.PRIVATE_WOUND },
      { kind: 'artifact', type: ArtifactType.CHARACTER_FUNCTION_AUDIT },
    ],
    promptTemplateId: 'p_10_earned_line',
    parserId: 'earned_line',
    outputArtifactType: ArtifactType.EARNED_LINE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.CALLBACK_MAP],
  },
  '11': {
    id: '11', phase: 'enrichment', name: "Reader's Grief Pass",
    description: 'Identify what the reader should mourn by the end. Even happy endings need cost.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.EARNED_LINE },
      { kind: 'artifact', type: ArtifactType.ARC_CLOSURE_REPORT },
    ],
    promptTemplateId: 'p_11_grief',
    parserId: 'grief_inventory',
    outputArtifactType: ArtifactType.GRIEF_INVENTORY,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.6,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.EARNED_LINE],
  },
  '12': {
    id: '12', phase: 'enrichment', name: 'Moral Aftertaste Pass',
    description: 'Revise the ending so the final aftertaste matches the story\'s deeper emotional question.',
    scope: 'arc',
    inputs: [
      { kind: 'artifact', type: ArtifactType.ISSUE_DRAFT, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.GRIEF_INVENTORY },
      { kind: 'artifact', type: ArtifactType.EMOTIONAL_QUESTION },
      { kind: 'artifact', type: ArtifactType.CALLBACK_MAP },
    ],
    promptTemplateId: 'p_12_moral_aftertaste',
    parserId: 'moral_aftertaste',
    outputArtifactType: ArtifactType.MORAL_AFTERTASTE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [ArtifactType.GRIEF_INVENTORY],
  },
  '12D': {
    id: '12D', phase: 'enrichment', name: '12D — Manual Only / Legacy Rewrite Pass',
    description: 'Final Script Revision — Disabled from default chain pending non-destructive rewrite',
    scope: 'episode',
    needsPriorContext: true,
    inputs: [
      { kind: 'artifact', type: ArtifactType.SCENE_STRUCTURE },
      { kind: 'artifact', type: ArtifactType.EARNED_LINE, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.CALLBACK_MAP },
      { kind: 'artifact', type: ArtifactType.VISUAL_MOTIF, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.QUIET_PANEL_PLAN, episodeRef: 'all' },
      { kind: 'artifact', type: ArtifactType.MORAL_AFTERTASTE },
      { kind: 'artifact', type: ArtifactType.GRIEF_INVENTORY },
      { kind: 'artifact', type: ArtifactType.PAGE_RHYTHM, episodeRef: 'all' }
    ],
    promptTemplateId: 'p_12D_final_script_revision',
    parserId: 'scene_structure',
    outputArtifactType: ArtifactType.SCENE_STRUCTURE,
    outputPayloadVersion: 1,
    defaultModel: 'gemini-pro',
    defaultTemperature: 0.7,
    registerFraming: { enabled: false, proseGuidance: {} },
    requires: [
      ArtifactType.SCENE_STRUCTURE,
      ArtifactType.EARNED_LINE,
      ArtifactType.CALLBACK_MAP,
      ArtifactType.VISUAL_MOTIF,
      ArtifactType.QUIET_PANEL_PLAN,
      ArtifactType.MORAL_AFTERTASTE,
      ArtifactType.GRIEF_INVENTORY,
      ArtifactType.PAGE_RHYTHM
    ],
  },
};

export const PASS_ORDER = [
  '0.0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7',
  '0.8', '0.8A', '0.8R', '0.8RA',
  '0.9', '0.9S', '0.9W', '0.9G', '0.9A', '0.12', '0.14',
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '12D'
];

export function getPassSpec(id: string): PassSpec | null {
  return passRegistry[id] ?? null;
}

export function getAllPassSpecs(): PassSpec[] {
  return PASS_ORDER
    .map(id => passRegistry[id])
    .filter((s): s is PassSpec => s !== undefined);
}
