import type { CharacterPosition } from './character';

export interface BeatPropEntry {
  label: string;        // "the hammer", "the satellite module"
  description: string;  // concrete visual: "standard claw hammer, wooden handle, steel head, no glow"
  appearsInPanels: number[]; // 0-indexed panel positions
}

export interface BeatPanelPlan {
  shotType: string;
  action: string;
  subtext?: string;
  direction?: string;
  dialogueIndices: number[]; // indices into beat.script.entries
  captionIndices: number[];  // indices into beat.script.entries
  characterPositions?: CharacterPosition[];
  // DA-042 — panel-level direction (VPS-populated).
  foreground?: string;
  midground?: string;
  background?: string;
  relationalStaging?: string;  // how characters share the frame
  directAddress?: boolean;
}

export type BeatType = 'ESTABLISHING' | 'DIALOGUE' | 'TABLEAU' | 'MEMORY_BLEED';

export interface CinematicBeat {
  id: string;
  fid: string;
  description: string;         // narrative prose — story/teleplay
  visualDescription?: string;  // image-prompt compact (D88)
  subtext: string;
  beatType?: BeatType;
  groundingEnsemble?: string;
  continuityAnchor?: string;
  direction?: string;          // camera note — production use
  panelCountOverride?: number; // D106: manual panel count, overrides line-count derivation
  characterIds: string[];
  contentStale?: boolean;
  visualsStale?: boolean;      // D212
  visualsStaleReason?: string;
  scriptStale?: boolean;       // D318
  scriptStaleReason?: string;
  panelPlanStale?: boolean;    // D212
  panelPlanStaleReason?: string;
  beatPageStale?: boolean;     // D212
  beatPageStaleReason?: string;
  letteringStale?: boolean;    // D212
  letteringStaleReason?: string;
  scriptVersion?: number;      // D212
  visualVersion?: number;      // D212
  layoutVersion?: number;      // D212
  pageVersion?: number;        // D212
  script?: BeatScript;         // textual realization — D89
  panelPlans?: BeatPanelPlan[]; // AI-generated panel breakdown
  panelProps?: BeatPropEntry[];   // DA-032: prop continuity
  visualDirection?: BeatVisualDirection;  // DA-039
  panelPlanSource?: 'ai-plan' | 'heuristic-plan' | 'none'; // D212A
  locked?: boolean;            // NEW: D209 - lock state for canon protection
  gndsSource?: 'preserved' | 'consolidated' | 'new';
  gndsArchived?: boolean;
  /** @deprecated D89 — use beat.script.lines */
  lines?: ScriptLine[];
}

/**
 * CaptionEntry — D96
 * A manually-typed narration box rendered in a comic panel.
 * Never auto-generated. Positioned in the script sequence relative to dialogue lines.
 * style controls the visual appearance of the box.
 *
 * Styles:
 *   yellow  — classic Marvel narration/caption (yellow fill, black border)
 *   white   — internal monologue or thought (white fill)
 *   grey    — time/location stamp (grey fill, subdued)
 *   none    — floating text with no box (used for sparse captions)
 *   character — internal monologue using character's accent color (D106)
 */
export interface CaptionEntry {
  kind: "caption";   // discriminant
  fid: string;       // unique ID: "{beatFid}-C{n}"
  text: string;
  style: "yellow" | "white" | "grey" | "none" | "character";
  characterHandle?: string;  // D106: for style='character', links to character accent color
}

/**
* BeatScript — the textual realization of a CinematicBeat.
* Lives on beat.script. Separate from beat narrative fields.
* Generated by stageLines. Edited in BeatDetailPanel.
* Read by teleplay formatter and assembleBeatContext.
*/
export interface BeatScript {
  lines: ScriptLine[];             // @deprecated D96 — use entries
  entries?: (ScriptLine | CaptionEntry)[];  // D96: ordered mixed sequence
  aiGenerated?: boolean;           // NEW: marks these lines as AI-authored
  gndsSourceId?: string;           // D354 bridge tracking
  // actionLines reserved for future per-beat action line editing
}

export interface ScriptLine {
  fid: string;
  characterHandle: string;
  text: string;
  parenthetical?: string;
  isDone: boolean;
  kind?: 'line';
  speakerName?: string;
  characterId?: string | null;
  displayName?: string;
  speakerClassification?: 'resolvedCharacter' | 'unresolvedSpeaker' | 'nonCharacterVoice' | 'unknown';
  canonicalSpeakerKey?: string;
  speakerDisplayLabel?: string;
}

// DA-042 — the page register: what every panel on the page shares,
// because they are the same moment in the same place. Panel-specific
// direction (shot, depth, blocking, expression) lives on BeatPanelPlan.
export interface BeatVisualDirection {
  lighting: string;          // scene light: source, colour, hardness
  mood: string;              // emotional atmosphere of the page
  emotionalRegister: string; // the beat's dramatic temperature
  environmentalDetail: string; // 'sparse' | 'moderate' | 'rich'
}
