import { BeatScript, BeatType, BeatPanelPlan, BeatPropEntry, BeatVisualDirection } from './beat';
import { generateUID } from '../domainUtils';

// ─── Identity ────────────────────────────────────────────────────────
export type UID = string;

// ─── Address format ──────────────────────────────────────────────────
// New segment codes: S=Season, I=Issue, A=Act, SC=Scene, PB=PageBeat
// Example: ECH-S1-I01-A2-SC04-PB07
// Generated by buildProductionAddress() in domainUtils.ts (DA-006).

// ─── Issue ───────────────────────────────────────────────────────────
// Replaces Episode as the primary production narrative unit.
// One Issue = one 22-page comic issue.
export interface Issue {
  uid: UID;
  showId: string;
  legacyEpisodeId: string;    // id of the archived Episode this was promoted from
  issueCode: string;          // e.g. 'ECH-I01'
  number: number;
  title: string;
  arcSummary?: string;
  acts: ProductionAct[];
  gndsArtifactId: string;     // the 12D artifact UID that produced this Issue
  promotedAt: number;
  status: 'active' | 'archived';
}

// ─── ProductionAct ───────────────────────────────────────────────────
// Structural division within an Issue. Equivalent to legacy Act.
export interface ProductionAct {
  uid: UID;
  number: number;
  title: string;
  scenes: ProductionScene[];
}

// ─── ProductionScene ─────────────────────────────────────────────────
// Dramatic/location unit within an Act. Contains PageBeats.
export interface ProductionScene {
  uid: UID;
  number: number;
  title: string;
  setting: string;
  dramaticWant: string;
  sceneFunction: string;
  pageBeats: PageBeat[];
  settingAnchorId?: string; // show.settingAnchors[].id
}

// ─── PageBeat ────────────────────────────────────────────────────────
// One production-sized story unit. Intended to support one comic page.
// Replaces CinematicBeat in the new model.
export interface PageBeat {
  uid: UID;
  address: string;            // e.g. 'ECH-S1-I01-A1-SC02-PB04'
  number: number;
  description: string;
  beatType: string;           // reuses BeatType values
  characterIds: string[];
  subtext: string;
  visualNote: string;
  direction: string;
  script?: BeatScript;        // dialogue from 0.9D / 12D
  productionPageUid?: UID;    // set when a ProductionPage is assigned
  gndsSource?: 'preserved' | 'new' | 'consolidated';
  panelCountOverride?: 1|2|3|4|5|6; // author-set panel count
  panelPlans?: BeatPanelPlan[];  // AI-generated panel breakdown
  panelProps?: BeatPropEntry[];   // DA-032: prop continuity
  panelPlanStale?: boolean;
  visualDirection?: BeatVisualDirection;  // DA-038: from 12V
  layoutName?: string;       // DA-047: VPS-chosen page layout
  focalPanelIndex?: number;  // DA-047
  isSplash?: boolean;        // DA-047
  contentHash?: string;       // DA-045: hash of narrative inputs
  scriptFingerprint?: string; // DA-045: hash of script entry shape
}

// ─── ProductionPage ──────────────────────────────────────────────────
// One comic page slot within an issue.
// This is what the Scene Workbench and Issue Compiler work with.
export interface ProductionPage {
  uid: UID;
  showId: string;
  issueUid: UID;
  pageBeatUid: UID;           // the PageBeat this page was created from
  source: 'gnds' | 'manual' | 'uploaded';
  status: 'planned' | 'generated' | 'approved' | 'lettered' | 'exported';
  approvedImageVersionUid?: UID;
  createdAt: number;
  updatedAt: number;
}

// ─── IssueManifest ───────────────────────────────────────────────────
// Canonical page order for a comic issue.
// pageOrder is the single source of truth for publication sequence.
export interface IssueManifest {
  uid: UID;
  showId: string;
  issueUid: UID;
  pageOrder: UID[];           // ProductionPage UIDs in publication sequence
  coverPageUid?: UID;
  updatedAt: number;
}

// ─── ImageVersion ────────────────────────────────────────────────────
// One image asset version attached to a ProductionPage.
// Replaces ComicGalleryEntry in the new model.
export interface ImageVersion {
  uid: UID;
  showId: string;
  productionPageUid: UID;     // always set — no orphans by design
  assetId: string;            // blob key in AssetStorage (unchanged)
  variantType: 'base' | 'refined' | 'lettered' | 'uploaded' | 'final';
  status: 'draft' | 'approved' | 'archived';
  generationMethod?: string;
  panelAssetIds?: string[];
  createdAt: number;
  metadata?: any;
}

// ─── PromotionRecord ─────────────────────────────────────────────────
// Written once per episode promotion. Maps old beatFid → new PageBeat UID.
// Used to reconnect pre-promotion gallery images after promotion.
export interface PromotionRecord {
  uid: UID;
  showId: string;
  legacyEpisodeId: string;
  issueUid: UID;
  gndsArtifactId: string;
  promotedAt: number;
  // key: old CinematicBeat fid  value: new PageBeat uid
  beatFidToPageBeatUid: Record<string, UID>;
}

export function createManualPageBeat(
  title: string,
  description: string,
  version: 'full' | 'compressed' | 'single'
): PageBeat {
  return {
    uid: generateUID(),
    address: `MANUAL-${generateUID().slice(0,8)}`,
    number: 0,  // will be set by insertion position
    description,
    beatType: 'DIALOGUE',
    characterIds: [],
    subtext: '',
    visualNote: `${title} (${version} version)`,
    direction: '',
    gndsSource: 'new',
  };
}

export interface PreflightWarning {
  scope: 'page' | 'scene' | 'issue' | 'show';
  showId: string;
  issueId: string;
  actNumber?: number;
  sceneNumber?: number;
  productionPageUid?: string;
  pageBeatUid?: string;
  panelUid?: string;
  scriptUnitIndex?: number;
  dialogueLineIndex?: number;
  identifier: string;
  speakerName: string;
  classification: 'unresolvedSpeaker' | 'missingPortrait' | 'other';
  severity: 'info' | 'warning' | 'blocking';
  message: string;
  sourceArtifactId?: string;
  sourcePass?: string;
}
